homeserverUrl: "https://t2bot.io"
accessToken: "YOUR_TOKEN_HERE"

# The format to use for group localparts
groupLocalpartFormat: "hashtag.{tag}"

# Where sync data and other related information should be stored
dataPath: "./storage"

# Settings for controlling how logging works
logging:
  file: logs/hashtagbot.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5